### PR TITLE
[fork/release/1.4] Backport signals parsing for LCOW

### PR DESCRIPTION
**Pull request by katiewasnothere**

### CODE REVIEW

**Comment by kevpar** [comment]
Looks like the commits are missing the cherry-pick info. Can you do `git cherry-pick -xs`?

**Comment by katiewasnothere** [comment]
Ah, wasn't sure if we wanted that still when merging from fork/master and not across forks. I'll update.

**Comment by katiewasnothere** [comment]
@kevpar  done

**Review by kevpar — APPROVED** [review]
LGTM

**Pull request merged**
