### PR TITLE
Fix pull fails on unexpected EOF

### PR DESCRIPTION
**Pull request by anmaxvl**
Currently, containerd doesn't restart pull when it encounters unexpected EOF of
blob strem withtout error codes.
There are cases where this lead to pull failure.
This commit tries to fix this issue.

Signed-off-by: Kohei Tokunaga <ktokunaga.mail@gmail.com>
(cherry picked from commit 7bc5aa74c2cf054b8e5a7982cad073c252fb5f4a)

### CODE REVIEW

**Comment by anmaxvl** [comment]
what's our approach in backporting fixes from upstream? do we backport from upstream into our `fork/master` and then cherry-pick from `fork/master` into `fork/release-*` or cherry-pick from upstream directly into `fork/release-*`?

**Comment by helsaawy** [comment]
I am unsure the backport approach, but lgtm regardless

**Comment by dcantah** [comment]
I was also a little curious if we'd ever backported a change from main into fork/release/1.4 but seems like we did here https://github.com/kevpar/containerd/pull/14. But Maksim I think the approach you laid out rings a bell

**Comment by dcantah** [comment]
This is a shoddy example as the change made isn't actually in upstream but we first got this into master and then brought it back to 1.4

master: https://github.com/kevpar/containerd/pull/10
1.4: https://github.com/kevpar/containerd/pull/11

Truth be told the happy path is if this change got into the upstream 1.4 branch and then we can just merge in all of the changes to 1.4.x at once instead of cherry-picking, but doesn't seem like that change will be getting backported. There *is* an example of us pulling in a change that was only added to main and not backported to 1.4 here though https://github.com/kevpar/containerd/pull/5

**Comment by anmaxvl** [comment]
Thanks, @dcantah . I agree that ideally the fix would make it into upstream 1.4 branch and we just merge it into our fork, but oh well. We probably should merge upstream 1.4 into our fork at some point. I'll draft this for now, until we get people back from vacation and can discuss this.

**Pull request closed without merging**
