### PR TITLE
Update toml dependency

### PR DESCRIPTION
**Pull request by anmaxvl**
As part of ongoing work to migrate to go modules kevpar/cri#35 [BurntSushi/toml][1]
package has been replaced by [pelletier/go-toml][2] in the following PR kevpar/cri#36.
This unfortunately broke containerd build through CRI repository, because vendored
in forked version of containerd still has a dependency on BurntSushi/toml.

This PR addresses the issue and similarly updates the TOML package. Containerd still
needs to be revendored into CRI fork.

[1]: https://github.com/BurntSushi/toml
[2]: https://github.com/pelletier/go-toml

### CODE REVIEW

**Comment by anmaxvl** [comment]
@katiewasnothere @kevpar @dcantah @helsaawy @ambarve @kiashok @msscotb PTAL

**Review by helsaawy — APPROVED** [review]

**Comment by kevpar** [comment]
Can you add a description of why this is needed?

**Comment by anmaxvl** [comment]
> Can you add a description of why this is needed?

@kevpar done

**Review by kevpar — APPROVED** [review]
LGTM

**Pull request merged**
