### PR TITLE
Add annotations to task update request api

### PR DESCRIPTION
**Pull request by katiewasnothere**
This change adds the "annotations" field for passing in container update requests. A corresponding upstream PR is [here](https://github.com/containerd/containerd/pull/4647). This PR is made to allow us to move forward with plumbing support for updating *COW containers while we wait for the aforementioned PR to be merged. 

(ps: note that I accidentally made a branch off of the kevpar fork. We should continue with the expectation in that devs push branches to private forks before PRing to this fork moving forward.) 

Signed-off-by: Kathryn Baldauf <kabaldau@microsoft.com>

### CODE REVIEW

**Comment by dcantah** [comment]
@katiewasnothere this is the exact same change as whats pushed against upstream correct?

**Comment by kevpar** [comment]
Does this need to be a cherry-pick? Usually we would just backport the change to 1.4 in upstream, then pull that in as part of our next release.

**Comment by katiewasnothere** [comment]
> Does this need to be a cherry-pick? Usually we would just backport the change to 1.4 in upstream, then pull that in as part of our next release.

This PR was made before the upstream PR was merged. Should this PR be changed to a cherry-pick? I can make the backport PR as well for 1.4 upstream

**Comment by kevpar** [comment]
> > Does this need to be a cherry-pick? Usually we would just backport the change to 1.4 in upstream, then pull that in as part of our next release.
> 
> This PR was made before the upstream PR was merged. Should this PR be changed to a cherry-pick? I can make the backport PR as well for 1.4 upstream

In general we should try to keep from putting unique changes into the containerd fork. Either through direct check-ins or cherry-picks. The best path is to backport the change to whatever release branch we are currently based on (release/1.4 in this case) and then merge that into the corresponding fork branch (fork/release/1.4).

**Comment by katiewasnothere** [comment]
Sounds good, I'll close this then.

**Pull request closed without merging**
