### PR TITLE
Update fork main to v1.6 commits

### PR DESCRIPTION
**Pull request by katiewasnothere**
This PR updates the fork/main branch by merging in main@v1.6.0. This PR specifically merges at the tag from upstream and creates a merge commit. This allows us to later grab the merge commit from our fork for use in creating our fork release branch for 1.6.

### CODE REVIEW

**Comment by katiewasnothere** [comment]
@kevpar PTAL when you get the chance 
@dcantah @anmaxvl @ambarve @helsaawy @kiashok @msscotb If anyone else can take a look too :)

**Review by anmaxvl — APPROVED** [review]

**Review by helsaawy — APPROVED** [review]

**Comment by kevpar** [comment]
Before we merge this, do we know if there is any payload in `fork/release/1.4` that isn't also in `fork/main`? If so, we should probably move that over first, otherwise we'll have to port it to `fork/main` _and_ `fork/release/1.6`.

**Comment by katiewasnothere** [comment]
@kevpar Do you specifically mean any payload that *we've* created and put in our `fork/release/1.4` branch?

**Comment by kevpar** [comment]
> @kevpar Do you specifically mean any payload that _we've_ created and put in our `fork/release/1.4` branch?

Yes. If upstream has payload like this it's probably fine. My point was just to make sure we don't lose payload in `fork/release/1.4` that we rely on currently.

**Comment by katiewasnothere** [comment]
After investigating more, it looks like the following PRs were made only in fork/release/1.4 by us and need to be cherry-picked to `fork/main`:

- https://github.com/kevpar/containerd/pull/28
- https://github.com/kevpar/containerd/pull/33
- https://github.com/kevpar/containerd/pull/21

I will cherry pick the commits from these in a separate PR then rebase this as necessary.

**Review by dcantah — APPROVED** [review]

**Review by dcantah — APPROVED** [review]

**Pull request merged**
