### PR TITLE
Add codeowners for our fork of containerd

### PR DESCRIPTION
**Pull request by katiewasnothere**
Signed-off-by: Kathryn Baldauf <kabaldau@microsoft.com>

### CODE REVIEW

**Comment by katiewasnothere** [comment]
Ping here @kevpar if you know if this will work since we're on a fork

**Comment by kevpar** [comment]
I haven't read the docs, but doubt it will work, since you can't even @ that team from outside the org. (@microsoft/containerplat)

**Comment by katiewasnothere** [comment]
@kevpar yeah that seems to be a "feature" of organization teams. We could explicitly add all of cplat here but otherwise we'd have no auto reviewer added.

**Comment by kevpar** [comment]
I'd say let's focus on getting owners set up for the Microsoft repos first then.

**Pull request closed without merging**
